QMK_MAPPING = {
"KC_ENTER": 0x28,
"KC_ENT": 0x28,
"KC_ESCAPE": 0x29,
"KC_ESC": 0x29,
"KC_BACKSPACE": 0x2a,
"KC_BSPC": 0x2a,
"KC_TAB": 0x2b,
"KC_SPACE": 0x2c,
"KC_SPC": 0x2c,
"KC_MINUS": 0x2d,
"KC_MINS": 0x2d,
"KC_EQUAL": 0x2e,
"KC_EQL": 0x2e,
"KC_LEFT_BRACKET": 0x2f,
"KC_LBRC": 0x2f,
"KC_RIGHT_BRACKET": 0x30,
"KC_RBRC": 0x30,
"KC_BACKSLASH": 0x31,
"KC_BSLS": 0x31,
"KC_NONUS_HASH": 0x32,
"KC_NUHS": 0x32,
"KC_SEMICOLON": 0x33,
"KC_SCLN": 0x33,
"KC_QUOTE": 0x34,
"KC_QUOT": 0x34,
"KC_GRAVE": 0x35,
"KC_GRV": 0x35,
"KC_COMMA": 0x36,
"KC_COMM": 0x36,
"KC_DOT": 0x37,
"KC_SLASH": 0x38,
"KC_SLSH": 0x38,
"KC_CAPS_LOCK": 0x39,
"KC_CAPS": 0x39,
"KC_F1": 0x3a,
"KC_F2": 0x3b,
"KC_F3": 0x3c,
"KC_F4": 0x3d,
"KC_F5": 0x3e,
"KC_F6": 0x3f,
"KC_F7": 0x40,
"KC_F8": 0x41,
"KC_F9": 0x42,
"KC_F10": 0x43,
"KC_F11": 0x44,
"KC_F12": 0x45,
"KC_PRINT_SCREEN": 0x46,
"KC_PSCR": 0x46,
"KC_SCROLL_LOCK": 0x47,
"KC_SCRL,": 0x47,
"KC_PAUSE": 0x48,
"KC_PAUS,": 0x48,
"KC_INSERT": 0x49,
"KC_INS": 0x49,
"KC_HOME": 0x4a,
"KC_PAGE_UP": 0x4b,
"KC_PGUP": 0x4b,
"KC_DELETE": 0x4c,
"KC_DEL": 0x4c,
"KC_END": 0x4d,
"KC_PAGE_DOWN": 0x4e,
"KC_PGDN": 0x4e,
"KC_RIGHT": 0x4f,
"KC_RGHT": 0x4f,
"KC_LEFT": 0x50,
"KC_DOWN": 0x51,
"KC_UP": 0x52,
"KC_NUM_LOCK": 0x53,
"KC_NUM": 0x53,
"KC_KP_SLASH": 0x54,
"KC_PSLS": 0x54,
"KC_KP_ASTERISK": 0x55,
"KC_PAST": 0x55,
"KC_KP_MINUS": 0x56,
"KC_PMNS": 0x56,
"KC_KP_PLUS": 0x57,
"KC_PPLS": 0x57,
"KC_KP_ENTER": 0x58,
"KC_PENT": 0x58,
"KC_KP_1": 0x59,
"KC_P1": 0x59,
"KC_KP_2": 0x5a,
"KC_P2": 0x5a,
"KC_KP_3": 0x5b,
"KC_P3": 0x5b,
"KC_KP_4": 0x5c,
"KC_P4": 0x5c,
"KC_KP_5": 0x5d,
"KC_P5": 0x5d,
"KC_KP_6": 0x5e,
"KC_P6": 0x5e,
"KC_KP_7": 0x5f,
"KC_P7": 0x5f,
"KC_KP_8": 0x60,
"KC_P8": 0x60,
"KC_KP_9": 0x61,
"KC_P9": 0x61,
"KC_KP_0": 0x62,
"KC_P0": 0x62,
"KC_KP_DOT": 0x63,
"KC_PDOT": 0x63,
"KC_NONUS_BACKSLASH": 0x64,
"KC_NUBS": 0x64,
"KC_APPLICATION": 0x65,
"KC_APP": 0x65,
"KC_KB_POWER": 0x66,
"KC_KP_EQUAL": 0x67,
"KC_PEQL": 0x67,
"KC_F13": 0x68,
"KC_F14": 0x69,
"KC_F15": 0x6a,
"KC_F16": 0x6b,
"KC_F17": 0x6c,
"KC_F18": 0x6d,
"KC_F19": 0x6e,
"KC_F20": 0x6f,
"KC_F21": 0x70,
"KC_F22": 0x71,
"KC_F23": 0x72,
"KC_F24": 0x73,
# "KC_EXECUTE": ,
# "KC_EXEC": ,
# "KC_HELP": ,
# "KC_MENU": ,
# "KC_SELECT": ,
# "KC_SLCT": ,
# "KC_STOP": ,
# "KC_AGAIN": ,
# "KC_AGIN": ,
# "KC_UNDO": ,
# "KC_CUT": ,
# "KC_COPY": ,
# "KC_PASTE": ,
# "KC_PSTE": ,
# "KC_FIND": ,
# "KC_KB_MUTE": ,
# "KC_KB_VOLUME_UP": ,
# "KC_KB_VOLUME_DOWN": ,
# "KC_LOCKING_CAPS_LOCK": ,
# "KC_LCAP": ,
# "KC_LOCKING_NUM_LOCK": ,
# "KC_LNUM": ,
# "KC_LOCKING_SCROLL_LOCK": ,
# "KC_LSCR": ,
# "KC_KP_COMMA": ,
# "KC_PCMM": ,
# "KC_KP_EQUAL_AS400": ,
# "KC_INTERNATIONAL_1": ,
# "KC_INT1": ,
# "KC_INTERNATIONAL_2": ,
# "KC_INT2": ,
# "KC_INTERNATIONAL_3": ,
# "KC_INT3": ,
# "KC_INTERNATIONAL_4": ,
# "KC_INT4": ,
# "KC_INTERNATIONAL_5": ,
# "KC_INT5": ,
# "KC_INTERNATIONAL_6": ,
# "KC_INT6": ,
# "KC_INTERNATIONAL_7": ,
# "KC_INT7": ,
# "KC_INTERNATIONAL_8": ,
# "KC_INT8": ,
# "KC_INTERNATIONAL_9": ,
# "KC_INT9": ,
# "KC_LANGUAGE_1": ,
# "KC_LNG1": ,
# "KC_LANGUAGE_2": ,
# "KC_LNG2": ,
# "KC_LANGUAGE_3": ,
# "KC_LNG3": ,
# "KC_LANGUAGE_4": ,
# "KC_LNG4": ,
# "KC_LANGUAGE_5": ,
# "KC_LNG5": ,
# "KC_LANGUAGE_6": ,
# "KC_LNG6": ,
# "KC_LANGUAGE_7": ,
# "KC_LNG7": ,
# "KC_LANGUAGE_8": ,
# "KC_LNG8": ,
# "KC_LANGUAGE_9": ,
# "KC_LNG9": ,
# "KC_ALTERNATE_ERASE": ,
# "KC_ERAS": ,
# "KC_SYSTEM_REQUEST": ,
# "KC_SYRQ": ,
# "KC_CANCEL": ,
# "KC_CNCL": ,
# "KC_CLEAR": ,
# "KC_CLR": ,
# "KC_PRIOR": ,
# "KC_PRIR": ,
# "KC_RETURN": ,
# "KC_RETN": ,
# "KC_SEPARATOR": ,
# "KC_SEPR": ,
# "KC_OUT": ,
# "KC_OPER": ,
# "KC_CLEAR_AGAIN": ,
# "KC_CLAG": ,
# "KC_CRSEL": ,
# "KC_CRSL": ,
# "KC_EXSEL": ,
# "KC_EXSL": ,
"KC_LEFT_CTRL": 0xe0,
"KC_LCTL": 0xe0,
"KC_LEFT_SHIFT": 0xe1,
"KC_LSFT": 0xe1,
"KC_LEFT_ALT": 0xe2,
"KC_LALT,": 0xe2,
"KC_LEFT_GUI": 0xe3,
"KC_LGUI,": 0xe3,
"KC_RIGHT_CTRL": 0xe4,
"KC_RCTL": 0xe4,
"KC_RIGHT_SHIFT": 0xe5,
"KC_RSFT": 0xe5,
"KC_RIGHT_ALT": 0xe6,
"KC_RALT,": 0xe6,
"KC_RIGHT_GUI": 0xe7,
"KC_RGUI,": 0xe7,
# "KC_SYSTEM_POWER": ,
# "KC_PWR": ,
# "KC_SYSTEM_SLEEP": ,
# "KC_SLEP": ,
# "KC_SYSTEM_WAKE": ,
# "KC_WAKE": ,
# "KC_AUDIO_MUTE": ,
# "KC_MUTE": ,
# "KC_AUDIO_VOL_UP": ,
# "KC_VOLU": ,
# "KC_AUDIO_VOL_DOWN": ,
# "KC_VOLD": ,
# "KC_MEDIA_NEXT_TRACK": ,
# "KC_MNXT": ,
# "KC_MEDIA_PREV_TRACK": ,
# "KC_MPRV": ,
# "KC_MEDIA_STOP": ,
# "KC_MSTP": ,
# "KC_MEDIA_PLAY_PAUSE": ,
# "KC_MPLY": ,
# "KC_MEDIA_SELECT": ,
# "KC_MSEL": ,
# "KC_MEDIA_EJECT": ,
# "KC_EJCT": ,
# "KC_MAIL": ,
# "KC_CALCULATOR": ,
# "KC_CALC": ,
# "KC_MY_COMPUTER": ,
# "KC_MYCM": ,
# "KC_WWW_SEARCH": ,
# "KC_WSCH": ,
# "KC_WWW_HOME": ,
# "KC_WHOM": ,
# "KC_WWW_BACK": ,
# "KC_WBAK": ,
# "KC_WWW_FORWARD": ,
# "KC_WFWD": ,
# "KC_WWW_STOP": ,
# "KC_WSTP": ,
# "KC_WWW_REFRESH": ,
# "KC_WREF": ,
# "KC_WWW_FAVORITES": ,
# "KC_WFAV": ,
# "KC_MEDIA_FAST_FORWARD": ,
# "KC_MFFD": ,
# "KC_MEDIA_REWIND": ,
# "KC_MRWD": ,
# "KC_BRIGHTNESS_UP": ,
# "KC_BRIU": ,
# "KC_BRIGHTNESS_DOWN": ,
# "KC_BRID": ,
}

def qmk_to_key_code(qmk_code):
    if not qmk_code.startswith("KC_"):
        raise ValueError("Not a keycode")
    if len(qmk_code) == 4:
        c = qmk_code[-1]
        if c.isalpha():
            return 0x4 + (ord(c.lower()) - ord('a'))
        else:
            if c == "0":
                return 0x27
            return 0x1d + int(c)
    if qmk_code in QMK_MAPPING:
        return QMK_MAPPING[qmk_code]
    print(qmk_code)
    return None